extraction:
  cpp:
    after_prepare: 
      - python report.py 74
  cobol:
    after_prepare: 
      - python report.py 74
  csharp:
    after_prepare: 
      - python report.py 74
  java:
    after_prepare: 
      - python report.py 74
  javascript:
    after_prepare: 
      - python report.py 74
  python:
    after_prepare: 
      - python report.py 74
